services:
    postgres:
        image: postgres:16
        container_name: postgres_identityserver
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres123
          POSTGRES_DB: identitydb
        ports:
          - "5432:5432"
        volumes:
          - C:\postgresql_identity:/var/lib/postgresql/data
        networks:
            - galaxy_security

networks:
  galaxy_security: 